name: Push to GCP
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy franzbot
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/franzbot-reborn
            git pull
          host: 35.212.198.25
          user: reiichi001
          key: ${{ secrets.PRIVATE_KEY}}
