name: Push to GCP
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy franzbot
        uses: fifsky/ssh-action@master
        with:
          command: |
            source ~/.bashrc
            pm2 restart "Franzbot Reborn";
          host: 35.212.198.25
          user: reiichi001
          key: ${{ secrets.PRIVATE_KEY}}
